# Generated by Django 3.2.5 on 2021-08-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_user_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='date',
        ),
    ]
