# Generated by Django 3.2.5 on 2021-08-03 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_user_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 13, 17, 56, 687369)),
        ),
    ]
