# Generated by Django 3.2.5 on 2021-08-03 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_user_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 7, 54, 3, 114409, tzinfo=utc)),
        ),
    ]
