# Generated by Django 3.2.5 on 2021-08-07 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_user_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 14, 43, 9, 477050)),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='discription',
            field=models.CharField(max_length=100000),
        ),
    ]
